### ISSUE TITLE
calcGef with beta=0 is not equal to g0

### ISSUE THREAD

**Issue by JonasGutermuth** [oscarperpinan/solar#14]
Why is the calculation of calcGef with beta=0 not equal to g0? Thanks for your help.

My test Code:
```
lat = 34.8363472
date = c("2017-12-14")
G0 = c(3600)
TempMax = c(30)
TempMin = c(0)
df = data.frame(date, G0, TempMax, TempMin)
bd=df2Meteo(df, dates.col='date', lat=lat, format='%Y-%m-%d')
g0 <- calcG0(lat=lat, modeRad='bd', dataRad=bd)
print(as.zooD(g0))

gef <- calcGef(lat = lat, modeRad = "prev", dataRad = g0, beta =0, alfa = 0)
print(as.zooD(gef))
```

**Comment by JonasGutermuth** [comment]
i found my problem. If I use hourly values it is working

**Comment by oscarperpinan** [comment]
`calcGef` computes the irradiation incident on a plane and the **effective** irradiation incident on a plane. The effective irradiation includes the losses due to dust and angular reflection. You can check the values of these irradiations printing the whole object `gef`:
```
> gef
Object of class  Gef 

Source of meteorological information: bd- 

Latitude of source:  34.8 degrees
Latitude for calculations:  34.8 degrees

Monthly averages:
              Bod      Bnd  Gd        Dd       Bd     Gefd      Defd     Befd
dic 2017 4.673151 7.199746 3.6 0.8140014 2.785999 3.084637 0.7128957 2.371741

Yearly values:
          Bod      Bnd  Gd        Dd       Bd     Gefd      Defd     Befd
2017 4.673151 7.199746 3.6 0.8140014 2.785999 3.084637 0.7128957 2.371741
-----------------
Mode of tracking:  fixed 
    Inclination:  0 
    Orientation:  0 
```

More information in `help(Gef-class)` and `help(fInclin)` and in the paper:

> Perpiñán, O. (2012), "solaR: Solar Radiation and Photovoltaic Systems with R", Journal of Statistical Software, 50(9), 1-32, <http://www.jstatsoft.org/v50/i09/>
