### ISSUE TITLE
calcG0 fails with custom meteo object

### ISSUE THREAD

**Issue by 0814celsus** [oscarperpinan/solar#17]
If using function dfI2Meteo it leads to a zoo object of class character which fails in calcG0. coredata from meteoobject needs to be transformed to numeric. 

in function fCompI  need to change 
G0 <- coredata(getG0(BD)) to  
G0 <- as.numeric(coredata(getG0(BD)))

**Comment by oscarperpinan** [comment]
Please, could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by BlaiseKelly** [comment]
Hi Oscar, I have also been struggling with a custom meteo object. I put together this reproducible example https://stackoverflow.com/questions/69873240/incident-solar-irradiation-on-inclinded-plane-using-solar hope you can help. I have struggled to get the only examples https://www.jstatsoft.org/article/view/v050i09 I can find to work also. Can you confirm they still work? Many thanks for putting this together!

**Comment by oscarperpinan** [comment]
Hello,
I have just [answered](https://stackoverflow.com/a/70086736/964866) your question. I think you have a problem with the timezone of the time series.

> Can you confirm they still work? 

Yes, sure, with the exception of the `readSIAR` function (deprecated). Most of the examples in this paper are included in the help pages of the functions of the package. The [check procedures](https://cran.r-project.org/web/checks/check_results_solaR.html) show no problem with the package.
