### ISSUE TITLE
Adopt maptools::sun-methods?

### ISSUE THREAD

**Issue by rsbivand** [oscarperpinan/solar#18]
Oscar,

Is it possible that this package could receive the sun-methods from `maptools` https://maptools.r-forge.r-project.org/reference/sun-methods.html? Some 6 CRAN packages use the methods, and as.maptools retires would see changes in results using for example `solartime`. Sebastian Luque, the author of the methods, would be happy to see them moved from `maptools`.

Roger

**Comment by oscarperpinan** [comment]
Hi Roger,

I am sorry but I am not interested in these methods. On the one hand, there are already functions in `solaR` that implement equations of solar geometry.  On the other hand, this package suggests `sp` and these methods would imply using `Depends` or `Imports`, and I don't want this change in the dependencies.

Perhaps Sebastian could publish these methods in a separate package.

**Comment by rsbivand** [comment]
Thanks, I understand. I'll follow up your suggestion.
